name: just_for_testing

on:
  pull_request:
  push:
    branches:
      - develop

jobs:
  changelog:
    categories:
      - title: ğŸ• Features
        labels:
          - '*'
        exclude:
          labels:
            - dependencies
      - title: ğŸ‘’ Dependencies
        labels:
          - dependencies